export const OP_CHANNELS = {
  Activate: 'op:activate',
  Deactivate: 'op:deactivate',
  RequestDeactivate: 'op:deactivate:request',
  RendererReady: 'op:renderer:ready',
  Cursor: 'op:cursor',
  GlobalContextMenu: 'op:global-context-menu',
  GlobalMouseDown: 'op:global-mouse-down',
  HoldProgress: 'op:hold:progress',
  SetInteractive: 'op:overlay:set-interactive',
  RequestWindowContext: 'op:window-context:request',
  RequestGrounding: 'op:grounding:request',
  ReadSelection: 'op:selection:read',
  InsertText: 'op:text:insert',
  CaptureActivity: 'op:capture:activity',
  SubmitInstruction: 'op:agent:submit',
  AgentEvent: 'op:agent:event',
  CuaTaskList: 'op:cua-task:list',
  CuaTaskCancel: 'op:cua-task:cancel',
  CuaTaskEvent: 'op:cua-task:event',
  ApproveAgentRequest: 'op:agent:approve',
  CancelRun: 'op:agent:cancel',
  GetSettings: 'op:settings:get',
  SaveSettings: 'op:settings:save',
  GetConversations: 'op:history:list',
  GetConversation: 'op:history:get',
  DeleteConversation: 'op:history:delete',
  FetchVisionModels: 'op:models:fetch-vision'
} as const;

export type OpChannel = (typeof OP_CHANNELS)[keyof typeof OP_CHANNELS];
